description: "Yo dawg, I herd u liek skeletons..."
variables:
  skeleton_name:
    prompt: Enter a name for your skeleton.
  closet:
    prompt: no
    default: __default__
  description:
    prompt: Enter a description for your skeleton.
  id:
    prompt: Enter a UUID for your skeleton.